### ISSUE TITLE
utf8-decode a los resultados de consultas

### ISSUE THREAD

**Issue by leandromusso** [leandromusso/nimbus-salud#12]
Algunas consultas no funcionan como por ejemplo:
`http://localhost/github/nimbus-salud/api.php?accion=obtener-partidos-provincia&id-provincia=1`
Debido a que el resultado contiene tildes. Pasar todos los resultados de las consultas por utf8-decode resuelve ese problema. Si querés pasar el array completo, podés usar array_map y en el callback poner utf8-decode, incluso podría ser una función

**Comment by AleFelix** [comment]
Me parece que no te va a servir este fix, estuve haciendo pruebas y aparentemente el problema es el `json_encode()` que según la documentación solo soporta strings que usen la codificación UTF-8.

Por lo que estuve probando, si a un string acentuado (que sacado de la BD debería estar en Latin1) le aplico `utf8_decode()` y después lo paso por `json_encode()`, la función me devuelve nulo.

Creo que la razón por la que se rompe es por que `utf8_decode()` esta hecho para convertir UTF-8 a Latin1, pero el texto de la BD ya esta en Latin1, por lo cual la decodificación falla y devuelve caracteres desconocidos que `json_encode()` no comprende.

No estoy seguro de por que funciona, pero creo que la solución es que a `json_encode` le pase una constante para que no trate de escapar los caracteres especiales, de manera que quede en `json_encode($respuesta, JSON_UNESCAPED_UNICODE)`. Estuve probando en el navegador y con esa constante me devuelve los acentos correctamente.

Igual te lo dejo con el `utf8_decode()` para que lo pruebes cuando haga el PR, solo te aviso para que sepas que si falla ya tengo un plan B.
