### ISSUE TITLE
enviar invitacion mail

### ISSUE THREAD

**Issue by leandromusso** [leandromusso/nimbus-salud#38]
La función anda ok, pero luego no tengo modo de pasarte el hash en el registro

**Comment by AleFelix** [comment]
¿En que parte del proceso de registro te parece que deberías enviarle el hash a la api para otorgarle al usuario la licencia de la invitación? ¿En la acción `actualizar-usuario`, o en una función separada? ¿Un usuario invitado sigue el flujo de registro normal? (`insertar-usuario`, `actualizar-usuario`, `activar-usuario`). Por otra parte, me parece que en este caso vamos a tener que bloquear la posibilidad de que el nuevo usuario seleccione el nivel Admin, ya que la licencia ya va a tener un administrador asociado. Ahora que lo pienso, tampoco tendría sentido que pueda seleccionar el tipo paciente.

**Comment by leandromusso** [comment]
creería que lo adecuado es que sea en actualizar-usuario
El usuario invitado sigue el flujo de registro normal
es correcto que no puede ser ni admin ni paciente, yo lo bloqueo en la UI, no te preocupes
