### ISSUE TITLE
enviar invitacion id

### ISSUE THREAD

**Issue by leandromusso** [leandromusso/nimbus-salud#39]
si el usuario no se puede loguear no tiene forma de ver las invitaciones recibidas. Esta función debería también enviar un email con una url para aceptar la invitación

**Comment by AleFelix** [comment]
Si entendí bien, en este caso necesitas una nueva función `aceptar-invitacion-mail` que te va a permitir aceptar la invitación referenciada en el hash sin necesidad de que el usuario este logueado.

**Comment by leandromusso** [comment]
exacto. La invitación siempre va a llegar por email con un link (configurable como el de activar usuario)
