### ISSUE TITLE
Parámetros obligatorios en actualizar-usuario

### ISSUE THREAD

**Issue by AleFelix** [leandromusso/nimbus-salud#42]
Tenía entendido que estos parámetros son obligatorios en el registro de un nuevo usuario:

- `nombre-apellido`
- `id-tipo-doc`
- `numero-doc`
- `fecha-nacimiento`
- `id-pais`
- `id-provincia`
- `id-partido`
- `id-localidad`
- `direccion`
- `cod-postal`

Sin embargo, desde el front-end parece que no se esta verificando si todos contienen información, por lo cual me puede llegar por ejemplo el parámetro del número de documento con un string vacío. La función `isset` de php toma los strings vacíos como válidos, por eso la api no se esta quejando.

Cambié la función `isset` por `empty` para no permitir strings vacíos, pero también quiero que me confirmes que todos esos parámetros son efectivamente obligatorios.

**Comment by leandromusso** [comment]
Estoy intentando hacer una arquitectura de pirámide, donde la UI sea bastante flexible y que las restricciones las pongan la API y la base de datos, por eso trato de no restringir mucho la UI. A medida que lo testeemos y recibamos feedback lo podemos ajustar, Por ejemplo, si muchos usuarios se quejan de llegar hasta el final y que recién ahí les indique que tienen que completar el nombre

**Comment by AleFelix** [comment]
Perfecto, entonces voy a mantener la verificación de los parámetros. 👍
