### ISSUE TITLE
Seleccionar Plan

### ISSUE THREAD

**Issue by leandromusso** [leandromusso/nimbus-salud#44]
El usuario no debería poder seleccionar el plan gratuito

**Comment by AleFelix** [comment]
La api asume que el tipo de licencia gratuita corresponde al `id` 1, no hay problema si lo querés cambiar por otro valor. Otra opción es no comparar por `id` y en su lugar hacer una consulta SQL para averiguar si el importe del tipo de plan es igual a cero.
