### ISSUE TITLE
historia clínica

### ISSUE THREAD

**Issue by leandromusso** [leandromusso/nimbus-salud#49]
La historia clínica debe ser un campo de turno. Agregarlo en la base de datos y modificar las funciones necesarias para poder agregar ese campo.
También se debe poder editar

**Comment by AleFelix** [comment]
SQL con los cambios:
```
ALTER TABLE `turnos` 
ADD COLUMN `historiaClinica` TEXT NULL AFTER `idMedicosUbicaciones`;
```

**Comment by AleFelix** [comment]
Acciones modificadas en la api:

- [obtener-turnos](https://github.com/leandromusso/nimbus-salud/wiki/Acciones-de-la-API#obtener-turnos)
- [insertar-turno](https://github.com/leandromusso/nimbus-salud/wiki/Acciones-de-la-API#insertar-turno)
- [editar-turno](https://github.com/leandromusso/nimbus-salud/wiki/Acciones-de-la-API#editar-turno)
- [obtener-practicas-dia](https://github.com/leandromusso/nimbus-salud/wiki/Acciones-de-la-API#obtener-practicas-dia)
- [obtener-turnos-totales](https://github.com/leandromusso/nimbus-salud/wiki/Acciones-de-la-API#obtener-turnos-totales)
- [obtener-detalles-pacientes](https://github.com/leandromusso/nimbus-salud/wiki/Acciones-de-la-API#obtener-detalles-pacientes)
- [obtener-datos-paciente](https://github.com/leandromusso/nimbus-salud/wiki/Acciones-de-la-API#obtener-datos-paciente)

**Comment by AleFelix** [comment]
Una duda, ¿Hay que hacer algún cambio en la tabla de detalles de turnos? Ya que cada detalle tiene su propio campo booleano `historiaClinicaPublica`, pero ahora la HC esta en el turno.

**Comment by leandromusso** [comment]
El campo de historiaClinicaPublica también debería pasar a turno.

Exacto, voy a agregar un editor WYSIWYG y en la base de datos metemos todo con formato. Por ahora las imágenes no van

**Comment by AleFelix** [comment]
SQL de `historiaClinicaPublica`:
```
ALTER TABLE `turnos` 
ADD COLUMN `historiaClinicaPublica` TINYINT(3) UNSIGNED NULL AFTER `historiaClinica`;
```
