### ISSUE TITLE
Permisos de pacientes en editar-turno

### ISSUE THREAD

**Issue by AleFelix** [leandromusso/nimbus-salud#50]
Actualmente la acción `editar-turno` permite editar estos campos:

- `fecha-hora`
- `id-estado`
- `importe-cobrado`
- `historia-clinica`

Dudas:

1) Actualmente la función puede ser llamada por profesionales, colaboradores y pacientes. ¿Esto es correcto?

2) Si el primer punto es correcto, ¿Que campos le debería permitir modificar al paciente?

**Comment by leandromusso** [comment]
El paciente solo puede cambiar el estado del turno de asignado a cancelado. El resto de los campos no
