### ISSUE TITLE
Vigencia de la agenda

### ISSUE THREAD

**Issue by leandromusso** [leandromusso/nimbus-salud#56]
Se deben pedir y completar las fechas de vigencia de las agendas. Esto debe repercutir al momento de seleccionar los turnos

**Comment by AleFelix** [comment]
Por ahora solo se va a hacer uso de los campos `vigenciaDesde` y `vigenciaHasta` en la tabla `medicos_ubicaciones_horarios`.

**Comment by AleFelix** [comment]
Resumen de como se controlan las colisiones:
- Control de colisiones de vigencias: Dos horarios en el mismo día de semana no pueden solapar sus horas si sus fechas de vigencia coinciden en alguno de sus días.
- Control de colisiones de horas: Dos rangos de horas colisionan si se solapan en cualquier punto, a excepción de las horas de inicio y fin (es decir, la hora de fin de un horario puede coincidir con la hora de inicio del siguiente). Ej: 12:00 a 13:00 no colisionaría con 13:00 a 18:00.

Dejo algunos puntos para analizar:
- Las vigencias en la BD son datetimes, pero como solo usamos las fechas, tal vez tendría sentido convertirlas a dates.
- Por ahora el sistema permite que el prestador establezca tantos rangos de horas como quiera en un mismo día de semana. Si bien de momento solo es posible establecer dos rangos distintos desde el front-end, puede que haya que controlar la cantidad cuando se puedan editar los horarios de las ubicaciones.
- Para evitar colisiones entre rangos de horas, añadí una verificación en la función de generación de los intervalos, pero no se si es del todo correcta:
Modifique la función para descartar el último intervalo si no entra en el rango de horas.
Por ejemplo, si en un rango de 13:00 a 13:30 uso un intervalo de 20 minutos, solo habrá un horario disponible a las 13:00, ya que el último intervalo tendría que ser de 13:20 a 13:40, pero el límite es hasta las 13:30.
Ahora que lo pienso, otra solución sería que el ultimo intervalo tenga un tiempo menor al establecido, por lo cual en este caso quedaría un último intervalo de 10 minutos de 13:20 a 13:30.
