### ISSUE TITLE
turnos reservados

### ISSUE THREAD

**Issue by leandromusso** [leandromusso/nimbus-salud#59]
Permitir configurar turnos reservados, o sea, determinados días y horarios, que solo figuren disponibles para uso interno, pero que no le figuren a los pacientes para ser tomados vía web

**Comment by AleFelix** [comment]
¿Esto sería un campo en `medicos_ubicaciones_horarios` para indicar si el rango es solo para uso interno? ¿Y desde el front-end como funcionaría? ¿Un tercer rango horario para uso interno, o un checkbox para los rangos ya armados?

**Comment by leandromusso** [comment]
yo lo veo como una nueva tabla que sea algo así como medicos_ubicaciones_horarios_reservados. En el frontend, al momento de asociar una ubicación, en el wizard que le pide los horarios hay que agregar un paso más, en el que le muestre como quedaría conformada la semana y le permita seleccionar los turnos que serían reservados. Entonces los guardaríamos como guardamos los turnos. Es importante también que se pueda editar eso, si querés lo conversamos el lunes, andá adelantando todo lo que puedas desde la API

**Comment by AleFelix** [comment]
Requisitos:
- En el modal de asignación de ubicaciones a un prestador, en el paso posterior a la asignación de los intervalos, se debe mostrar un almanaque con una vista previa de como quedarían los horarios de atención.
- En dicho almanaque, el prestador/colaborador debe poder seleccionar cuales turnos quedarían reservados para uso interno.
- El estado de estos turnos debe ser `Para uso interno` y solo deben ser visibles desde el panel del prestador/colaborador.
- El buscador de turnos del paciente no debe mostrar los horarios de uso interno.

Nota: Posibles campos de la tabla `medicos_ubicaciones_horarios_reservados`: `diaSemana`, `hora` y `idMedicosUbicaciones`.

**Comment by AleFelix** [comment]
Esto podría tener conflicto con las vigencias de los horarios de las ubicaciones. Creo que la solución sería que `medicos_ubicaciones_horarios_reservados` haga referencia a `medicos_ubicaciones_horarios` en vez de a `medicos_ubicaciones`.

Por lo tanto, sus campos serían: `idMedicosUbicacionesHorarios` y `hora`, ya que el campo `diaSemana` ya esta presente en la tabla padre `medicos_ubicaciones_horarios`.

**Comment by leandromusso** [comment]
correcto, la relación es a `medicos_ubicaciones_horarios` y solo se guardaría la hora

**Comment by AleFelix** [comment]
SQL tabla:
```
CREATE TABLE `medicos_ubicaciones_horarios_reservados` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idMedicosUbicacionesHorarios` INT UNSIGNED NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`id`));
```
