### ISSUE TITLE
Permitir reacomodar turnos

### ISSUE THREAD

**Issue by AleFelix** [leandromusso/nimbus-salud#62]
En caso de que ocurra un inconveniente, es necesario que un prestador/colaborador pueda cancelar y reasignar todos los turnos en estado `Asignado` (y puede que también los que tienen estado `En Espera`) dentro de un cierto rango de fechas/horas.

Para esto se proponen los siguientes cambios:
- Dos nuevos estados de turnos: `A reasignar` y `Reasignado`.
- Cuando un turno ya asignado es cancelado por esta función, su estado pasa a ser `A reasignar`.
- La vista del prestador/colaborador debe tener una sección que liste los turnos en estado `A reasignar`.
- Al seleccionar un turno a reasignar, se debe abrir la agenda de turnos para que el prestador/colaborador indique la nueva fecha del mismo. La información del viejo turno debe ser copiada automáticamente.
- Al reasignar el turno, el viejo turno debe pasar a estado `Reasignado`.
- La lista de turnos en estado `A reasignar` tiene que mostrar los datos de contacto del paciente para que el colaborador pueda contactarse y acordar la nueva fecha. También tendría que tener la opción de cancelar el turno definitivamente.

**Comment by leandromusso** [comment]
Creería que el estado `Reasignado` no es necesario pero si lo ves útil hacelo

**Comment by AleFelix** [comment]
Ya tengo funcionando la sección del front-end que muestra la lista de turnos a reasignar y permite reacomodarlos en otra fecha/hora/ubicación, pero ahora me surge una duda con respecto al momento en que esos turnos son marcados con el estado `A reasignar`.

Según lo que habíamos establecido:
>En caso de que ocurra un inconveniente, es necesario que un prestador/colaborador pueda cancelar y reasignar todos los turnos dentro de un cierto rango de fechas/horas.

¿Para hacer esta parte debería añadir otra sección en el front-end que permita suspender todos los turnos dentro de un rango de fechas?

Se me ocurre que podría ser así:
- Nueva sección "Suspender turnos".
- Entradas: Ubicación, fechaHoraDesde, fechaHoraHasta, Medico (Si el usuario logueado es colaborador).
- Al hacer la búsqueda, lista todos los turnos Asignados/En espera entre los horarios ingresados (nombrePaciente, fecha, hora).
- Luego de generada la lista de turnos, mostrar un mensaje de advertencia "¿Esta seguro que desea suspender todos los turnos encontrados?".
- Debajo del mensaje mostrar un botón "Suspender turnos" que pasa todos los turnos de la lista a estado `A reasignar`.

**Comment by leandromusso** [comment]
Me parece perfecto!
